db_path: processed_images.db
duplicate_threshold: 0.3
match_threshold: 0.4
matcher: BF  # Доступные: BF, FLANN, SM
feature_extractor: ORB # Доступные: SIFT, ORB, KAZE, AKAZE
quality_method: BRISQUE #BRISQUE
